name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: high-ace-306706
  REGION: us-east1-b
  SERVICE_NAME: my-nestjs-service
  ECR_REPO: nestjs-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Google Cloud SDK và xác thực với service account key được lưu trong GitHub Secrets (GCP_SA_KEY)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Cấu hình Docker để push image lên Container Registry/Artifact Registry của GCP
      - name: Configure Docker for gcloud
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin gcr.io

      - name: Get Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA} -f DockerfileSTG .
      
      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA}

      # Deploy Cloud Run, mount secret file env từ Secret Manager vào container runtime
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE_NAME} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --mount-secrets=/etc/secrets/env-config=env-config:latest
