name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: high-ace-306706
  REGION: us-central1
  SERVICE_NAME: my-nestjs-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Google Cloud SDK và xác thực với service account key được lưu trong GitHub Secrets (GCP_SA_KEY)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Cấu hình Docker để push image lên Container Registry/Artifact Registry của GCP
      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker

      # Build image Docker cho ứng dụng NestJS
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} .

      # Push image Docker lên Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}

      # Deploy Cloud Run, mount secret file env từ Secret Manager vào container runtime
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE_NAME} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --mount-secrets=/etc/secrets/env-config=env-config:latest
