name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: high-ace-306706
  PROJECT_NUMBER: '137245003259'
  REGION: us-central1
  SERVICE_NAME: nestjs-demo-service
  ECR_REPO: nestjs-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Google Cloud SDK và xác thực với service account key được lưu trong GitHub Secrets (GCP_SA_KEY)
      - name: Auth gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Retrieve Secrets and Save to .env
        run: |
          gcloud secrets versions access latest --secret=nestjs-demo-env --format="get(payload.data)" | tr '_-' '/+' | base64 -d > envfile
          cat envfile

      # Cấu hình Docker để push image lên Container Registry/Artifact Registry của GCP
      - name: Configure Docker for gcloud
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin gcr.io

      - name: Get Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          cat Dockerfile
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA} . --no-cache

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA}

      # Deploy Cloud Run, mount secret file env từ Secret Manager vào container runtime
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE_NAME} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ECR_REPO}/${SERVICE_NAME}:${COMMIT_SHA} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --update-secrets=.env=projects/${PROJECT_NUMBER}/secrets/nestjs-demo-env:latest
